import db from "../config/dbConnect";
import { logger } from "../util/logger";

type SeedProduct = {
  product_name: string;
  product_category: string;
  product_image_url: string;
  description: string;
  price: number;
  stock_quantity: number;
};

const products: SeedProduct[] = [
  { product_name: "Wireless Mouse", product_category: "Electronics", product_image_url: "https://picsum.photos/seed/mouse/600/400", description: "Ergonomic wireless mouse with adjustable DPI.", price: 24.99, stock_quantity: 50 },
  { product_name: "Smart Watch", product_category: "Wearables", product_image_url: "https://picsum.photos/seed/watch/600/400", description: "Fitness smartwatch with heart rate monitor.", price: 149.99, stock_quantity: 15 },
  // NOTE: source data for this row was truncated in the terminal output you
  // pasted (description/price/stock never showed up on screen) — placeholder
  // values below, please verify against the real row.
  { product_name: "USB-C Charger", product_category: "Accessories", product_image_url: "https://picsum.photos/seed/charger/600/400", description: "USB-C fast charging cable and adapter.", price: 19.99, stock_quantity: 60 },
  { product_name: "Laptop Stand", product_category: "Accessories", product_image_url: "https://picsum.photos/seed/laptopstand/600/400", description: "Adjustable aluminum laptop stand.", price: 34.99, stock_quantity: 40 },
  { product_name: "Webcam HD", product_category: "Electronics", product_image_url: "https://picsum.photos/seed/webcam/600/400", description: "1080p webcam with built-in microphone.", price: 54.99, stock_quantity: 35 },
  { product_name: "Office Chair", product_category: "Furniture", product_image_url: "https://picsum.photos/seed/chair/600/400", description: "Ergonomic office chair with lumbar support.", price: 189.99, stock_quantity: 12 },
  { product_name: "Standing Desk", product_category: "Furniture", product_image_url: "https://picsum.photos/seed/desk/600/400", description: "Height adjustable standing desk.", price: 299.99, stock_quantity: 10 },
  { product_name: "Coffee Mug", product_category: "Kitchen", product_image_url: "https://picsum.photos/seed/mug/600/400", description: "350ml ceramic coffee mug.", price: 12.50, stock_quantity: 80 },
  { product_name: "Desk Lamp", product_category: "Home", product_image_url: "https://picsum.photos/seed/lamp/600/400", description: "LED desk lamp with adjustable brightness.", price: 32.99, stock_quantity: 30 },
  { product_name: "Notebook", product_category: "Stationery", product_image_url: "https://picsum.photos/seed/notebook/600/400", description: "Hardcover notebook with ruled pages.", price: 8.99, stock_quantity: 120 },
  { product_name: "Ballpoint Pen Set", product_category: "Stationery", product_image_url: "https://picsum.photos/seed/pens/600/400", description: "Pack of 10 smooth writing pens.", price: 6.99, stock_quantity: 200 },
  { product_name: "Wireless Earbuds", product_category: "Electronics", product_image_url: "https://picsum.photos/seed/earbuds/600/400", description: "Noise-cancelling wireless earbuds.", price: 99.99, stock_quantity: 28 },
  { product_name: "Monitor 27 Inch", product_category: "Electronics", product_image_url: "https://picsum.photos/seed/monitor/600/400", description: "27-inch Full HD IPS monitor.", price: 229.99, stock_quantity: 18 },
  { product_name: "External SSD 1TB", product_category: "Storage", product_image_url: "https://picsum.photos/seed/ssd/600/400", description: "High-speed portable 1TB SSD.", price: 139.99, stock_quantity: 22 },
  { product_name: "Essence Mascara Lash Princess", product_category: "Beauty", product_image_url: "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp", description: "A popular Essence Mascara Lash Princess beauty essential, valued for quality and everyday reliability.", price: 9.99, stock_quantity: 150 },
  { product_name: "Powder Canister", product_category: "Beauty", product_image_url: "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp", description: "A popular Powder Canister beauty essential, valued for quality and everyday reliability.", price: 14.99, stock_quantity: 150 },
  { product_name: "Dior J'adore", product_category: "Fragrances", product_image_url: "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp", description: "A signature Dior J'adore fragrance with a long-lasting, distinctive scent.", price: 89.99, stock_quantity: 80 },
  { product_name: "Dolce Shine Eau de", product_category: "Fragrances", product_image_url: "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp", description: "A signature Dolce Shine Eau de fragrance with a long-lasting, distinctive scent.", price: 69.99, stock_quantity: 80 },
  { product_name: "Annibale Colombo Bed", product_category: "Furniture", product_image_url: "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp", description: "A well-crafted Annibale Colombo Bed, combining comfort with durable, quality construction.", price: 1899.99, stock_quantity: 15 },
  { product_name: "Knoll Saarinen Executive Conference Chair", product_category: "Furniture", product_image_url: "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp", description: "A well-crafted Knoll Saarinen Executive Conference Chair, combining comfort with durable, quality construction.", price: 499.99, stock_quantity: 40 },
  { product_name: "Apple", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp", description: "Fresh Apple, a household grocery staple sourced for quality and value.", price: 1.99, stock_quantity: 150 },
  { product_name: "Cat Food", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp", description: "Fresh Cat Food, a household grocery staple sourced for quality and value.", price: 8.99, stock_quantity: 150 },
  { product_name: "Cooking Oil", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp", description: "Fresh Cooking Oil, a household grocery staple sourced for quality and value.", price: 4.99, stock_quantity: 150 },
  { product_name: "Dog Food", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp", description: "Fresh Dog Food, a household grocery staple sourced for quality and value.", price: 10.99, stock_quantity: 150 },
  { product_name: "Eggs", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp", description: "Fresh Eggs, a household grocery staple sourced for quality and value.", price: 2.99, stock_quantity: 150 },
  { product_name: "Fish Steak", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp", description: "Fresh Fish Steak, a household grocery staple sourced for quality and value.", price: 14.99, stock_quantity: 150 },
  { product_name: "Green Bell Pepper", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp", description: "Fresh Green Bell Pepper, a household grocery staple sourced for quality and value.", price: 1.29, stock_quantity: 150 },
  { product_name: "Green Chili Pepper", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp", description: "Fresh Green Chili Pepper, a household grocery staple sourced for quality and value.", price: 0.99, stock_quantity: 150 },
  { product_name: "Ice Cream", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp", description: "Fresh Ice Cream, a household grocery staple sourced for quality and value.", price: 5.49, stock_quantity: 150 },
  { product_name: "Milk", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/milk/thumbnail.webp", description: "Fresh Milk, a household grocery staple sourced for quality and value.", price: 3.49, stock_quantity: 150 },
  { product_name: "Potatoes", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp", description: "Fresh Potatoes, a household grocery staple sourced for quality and value.", price: 2.29, stock_quantity: 150 },
  { product_name: "Protein Powder", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/protein-powder/thumbnail.webp", description: "Fresh Protein Powder, a household grocery staple sourced for quality and value.", price: 19.99, stock_quantity: 150 },
  { product_name: "Soft Drinks", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp", description: "Fresh Soft Drinks, a household grocery staple sourced for quality and value.", price: 1.99, stock_quantity: 150 },
  { product_name: "Mechanical Keyboard", product_category: "Electronics", product_image_url: "https://cdn.dummyjson.com/product-images/86/thumbnail.jpg", description: "RGB mechanical keyboard with blue switches.", price: 79.99, stock_quantity: 30 },
  { product_name: "Gaming Headset", product_category: "Gaming", product_image_url: "https://cdn.dummyjson.com/product-images/87/thumbnail.jpg", description: "Surround sound gaming headset with microphone.", price: 69.99, stock_quantity: 25 },
  { product_name: "Bluetooth Speaker", product_category: "Electronics", product_image_url: "https://cdn.dummyjson.com/product-images/11/thumbnail.jpg", description: "Portable waterproof Bluetooth speaker.", price: 45.00, stock_quantity: 20 },
  { product_name: "Water Bottle", product_category: "Fitness", product_image_url: "https://cdn.dummyjson.com/product-images/91/thumbnail.jpg", description: "Insulated stainless steel water bottle.", price: 19.99, stock_quantity: 70 },
  { product_name: "Tissue Paper Box", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp", description: "Fresh Tissue Paper Box, a household grocery staple sourced for quality and value.", price: 2.49, stock_quantity: 150 },
  { product_name: "Water", product_category: "Groceries", product_image_url: "https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp", description: "Fresh Water, a household grocery staple sourced for quality and value.", price: 0.99, stock_quantity: 150 },
  { product_name: "Family Tree Photo Frame", product_category: "Home Decoration", product_image_url: "https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp", description: "A charming Family Tree Photo Frame to add character and warmth to any living space.", price: 29.99, stock_quantity: 80 },
  { product_name: "Plant Pot", product_category: "Home Decoration", product_image_url: "https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/thumbnail.webp", description: "A charming Plant Pot to add character and warmth to any living space.", price: 14.99, stock_quantity: 150 },
  { product_name: "Bamboo Spatula", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/bamboo-spatula/thumbnail.webp", description: "A durable Bamboo Spatula, an essential tool for everyday kitchen use.", price: 7.99, stock_quantity: 150 },
  { product_name: "Black Whisk", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp", description: "A durable Black Whisk, an essential tool for everyday kitchen use.", price: 9.99, stock_quantity: 150 },
  { product_name: "Egg Slicer", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp", description: "A durable Egg Slicer, an essential tool for everyday kitchen use.", price: 6.99, stock_quantity: 150 },
  { product_name: "Electric Stove", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp", description: "A durable Electric Stove, an essential tool for everyday kitchen use.", price: 49.99, stock_quantity: 80 },
  { product_name: "Hand Blender", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp", description: "A durable Hand Blender, an essential tool for everyday kitchen use.", price: 34.99, stock_quantity: 80 },
  { product_name: "Kitchen Sieve", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/kitchen-sieve/thumbnail.webp", description: "A durable Kitchen Sieve, an essential tool for everyday kitchen use.", price: 7.99, stock_quantity: 150 },
  { product_name: "Knife", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/knife/thumbnail.webp", description: "A durable Knife, an essential tool for everyday kitchen use.", price: 14.99, stock_quantity: 150 },
  { product_name: "Lunch Box", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/lunch-box/thumbnail.webp", description: "A durable Lunch Box, an essential tool for everyday kitchen use.", price: 12.99, stock_quantity: 150 },
  { product_name: "Pan", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp", description: "A durable Pan, an essential tool for everyday kitchen use.", price: 24.99, stock_quantity: 80 },
  { product_name: "Plate", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/plate/thumbnail.webp", description: "A durable Plate, an essential tool for everyday kitchen use.", price: 3.99, stock_quantity: 150 },
  { product_name: "Silver Pot With Glass Cap", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/silver-pot-with-glass-cap/thumbnail.webp", description: "A durable Silver Pot With Glass Cap, an essential tool for everyday kitchen use.", price: 39.99, stock_quantity: 80 },
  { product_name: "Yellow Peeler", product_category: "Kitchen Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/kitchen-accessories/yellow-peeler/thumbnail.webp", description: "A durable Yellow Peeler, an essential tool for everyday kitchen use.", price: 5.99, stock_quantity: 150 },
  { product_name: "Asus Zenbook Pro Dual Screen Laptop", product_category: "Laptops", product_image_url: "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp", description: "A powerful Asus Zenbook Pro Dual Screen Laptop, built for performance, portability, and everyday productivity.", price: 1799.99, stock_quantity: 15 },
  { product_name: "Lenovo Yoga 920", product_category: "Laptops", product_image_url: "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp", description: "A powerful Lenovo Yoga 920, built for performance, portability, and everyday productivity.", price: 1099.99, stock_quantity: 15 },
  { product_name: "Man Short Sleeve Shirt", product_category: "Men's Shirts", product_image_url: "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp", description: "A comfortable Man Short Sleeve Shirt, made from quality fabric for everyday wear.", price: 19.99, stock_quantity: 150 },
  { product_name: "Nike Baseball Cleats", product_category: "Men's Shoes", product_image_url: "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp", description: "A stylish pair of Nike Baseball Cleats, designed for comfort, support, and everyday durability.", price: 79.99, stock_quantity: 80 },
  { product_name: "Puma Future Rider Trainers", product_category: "Men's Shoes", product_image_url: "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp", description: "A stylish pair of Puma Future Rider Trainers, designed for comfort, support, and everyday durability.", price: 89.99, stock_quantity: 80 },
  { product_name: "Sports Sneakers Off White & Red", product_category: "Men's Shoes", product_image_url: "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp", description: "A stylish pair of Sports Sneakers Off White & Red, designed for comfort, support, and everyday durability.", price: 119.99, stock_quantity: 40 },
  { product_name: "Sports Sneakers Off White Red", product_category: "Men's Shoes", product_image_url: "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp", description: "A stylish pair of Sports Sneakers Off White Red, designed for comfort, support, and everyday durability.", price: 109.99, stock_quantity: 40 },
  { product_name: "Rolex Datejust", product_category: "Men's Watches", product_image_url: "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/thumbnail.webp", description: "A premium Rolex Datejust, crafted with precision for timeless, everyday elegance.", price: 10999.99, stock_quantity: 5 },
  { product_name: "Rolex Submariner Watch", product_category: "Men's Watches", product_image_url: "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp", description: "A premium Rolex Submariner Watch, crafted with precision for timeless, everyday elegance.", price: 13999.99, stock_quantity: 5 },
  { product_name: "Apple AirPods Max Silver", product_category: "Mobile Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp", description: "A reliable Apple AirPods Max Silver, designed to complement and enhance your mobile devices.", price: 549.99, stock_quantity: 40 },
  { product_name: "Apple Airpower Wireless Charger", product_category: "Mobile Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp", description: "A reliable Apple Airpower Wireless Charger, designed to complement and enhance your mobile devices.", price: 79.99, stock_quantity: 80 },
  { product_name: "Apple HomePod Mini Cosmic Grey", product_category: "Mobile Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp", description: "A reliable Apple HomePod Mini Cosmic Grey, designed to complement and enhance your mobile devices.", price: 99.99, stock_quantity: 80 },
  { product_name: "Apple iPhone Charger", product_category: "Mobile Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp", description: "A reliable Apple iPhone Charger, designed to complement and enhance your mobile devices.", price: 19.99, stock_quantity: 150 },
  { product_name: "Tartan Dress", product_category: "Tops", product_image_url: "https://cdn.dummyjson.com/product-images/tops/tartan-dress/thumbnail.webp", description: "A stylish Tartan Dress, made from quality fabric for a comfortable, flattering fit.", price: 39.99, stock_quantity: 80 },
  { product_name: "Apple MagSafe Battery Pack", product_category: "Mobile Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp", description: "A reliable Apple MagSafe Battery Pack, designed to complement and enhance your mobile devices.", price: 99.99, stock_quantity: 80 },
  { product_name: "Apple Watch Series 4 Gold", product_category: "Mobile Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp", description: "A reliable Apple Watch Series 4 Gold, designed to complement and enhance your mobile devices.", price: 349.99, stock_quantity: 40 },
  { product_name: "iPhone 12 Silicone Case with MagSafe Plum", product_category: "Mobile Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp", description: "A reliable iPhone 12 Silicone Case with MagSafe Plum, designed to complement and enhance your mobile devices.", price: 29.99, stock_quantity: 80 },
  { product_name: "Selfie Lamp with iPhone", product_category: "Mobile Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp", description: "A reliable Selfie Lamp with iPhone, designed to complement and enhance your mobile devices.", price: 14.99, stock_quantity: 150 },
  { product_name: "Generic Motorcycle", product_category: "Motorcycle", product_image_url: "https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp", description: "A high-performance Generic Motorcycle, built for power, control, and reliability on the road.", price: 3999.99, stock_quantity: 15 },
  { product_name: "MotoGP CI.H1", product_category: "Motorcycle", product_image_url: "https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/thumbnail.webp", description: "A high-performance MotoGP CI.H1, built for power, control, and reliability on the road.", price: 14999.99, stock_quantity: 5 },
  { product_name: "Sportbike Motorcycle", product_category: "Motorcycle", product_image_url: "https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp", description: "A high-performance Sportbike Motorcycle, built for power, control, and reliability on the road.", price: 7499.99, stock_quantity: 15 },
  { product_name: "Vaseline Men Body and Face Lotion", product_category: "Skin Care", product_image_url: "https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp", description: "A gentle, effective Vaseline Men Body and Face Lotion formulated for daily skin care and hydration.", price: 9.99, stock_quantity: 150 },
  { product_name: "iPhone 6", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp", description: "The iPhone 6, a feature-packed smartphone offering strong performance and reliability.", price: 299.99, stock_quantity: 40 },
  { product_name: "iPhone 13 Pro", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp", description: "The iPhone 13 Pro, a feature-packed smartphone offering strong performance and reliability.", price: 1099.99, stock_quantity: 15 },
  { product_name: "Oppo F19 Pro Plus", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp", description: "The Oppo F19 Pro Plus, a feature-packed smartphone offering strong performance and reliability.", price: 399.99, stock_quantity: 40 },
  { product_name: "Oppo K1", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/thumbnail.webp", description: "The Oppo K1, a feature-packed smartphone offering strong performance and reliability.", price: 299.99, stock_quantity: 40 },
  { product_name: "Realme C35", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/thumbnail.webp", description: "The Realme C35, a feature-packed smartphone offering strong performance and reliability.", price: 149.99, stock_quantity: 40 },
  { product_name: "Realme X", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp", description: "The Realme X, a feature-packed smartphone offering strong performance and reliability.", price: 299.99, stock_quantity: 40 },
  { product_name: "Realme XT", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp", description: "The Realme XT, a feature-packed smartphone offering strong performance and reliability.", price: 349.99, stock_quantity: 40 },
  { product_name: "Samsung Galaxy S8", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp", description: "The Samsung Galaxy S8, a feature-packed smartphone offering strong performance and reliability.", price: 499.99, stock_quantity: 40 },
  { product_name: "Vivo S1", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/thumbnail.webp", description: "The Vivo S1, a feature-packed smartphone offering strong performance and reliability.", price: 249.99, stock_quantity: 40 },
  { product_name: "Vivo V9", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/thumbnail.webp", description: "The Vivo V9, a feature-packed smartphone offering strong performance and reliability.", price: 299.99, stock_quantity: 40 },
  { product_name: "Vivo X21", product_category: "Smartphones", product_image_url: "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp", description: "The Vivo X21, a feature-packed smartphone offering strong performance and reliability.", price: 499.99, stock_quantity: 40 },
  { product_name: "American Football", product_category: "Sports Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/sports-accessories/american-football/thumbnail.webp", description: "A durable American Football, built for performance and reliability during active play.", price: 19.99, stock_quantity: 150 },
  { product_name: "Baseball Ball", product_category: "Sports Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp", description: "A durable Baseball Ball, built for performance and reliability during active play.", price: 8.99, stock_quantity: 150 },
  { product_name: "Basketball Rim", product_category: "Sports Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp", description: "A durable Basketball Rim, built for performance and reliability during active play.", price: 39.99, stock_quantity: 80 },
  { product_name: "Cricket Bat", product_category: "Sports Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-bat/thumbnail.webp", description: "A durable Cricket Bat, built for performance and reliability during active play.", price: 29.99, stock_quantity: 80 },
  { product_name: "Feather Shuttlecock", product_category: "Sports Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/sports-accessories/feather-shuttlecock/thumbnail.webp", description: "A durable Feather Shuttlecock, built for performance and reliability during active play.", price: 5.99, stock_quantity: 150 },
  { product_name: "Volleyball", product_category: "Sports Accessories", product_image_url: "https://cdn.dummyjson.com/product-images/sports-accessories/volleyball/thumbnail.webp", description: "A durable Volleyball, built for performance and reliability during active play.", price: 11.99, stock_quantity: 150 },
  { product_name: "Classic Sun Glasses", product_category: "Sunglasses", product_image_url: "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp", description: "A stylish pair of Classic Sun Glasses, offering UV protection with a modern look.", price: 24.99, stock_quantity: 80 },
  { product_name: "Party Glasses", product_category: "Sunglasses", product_image_url: "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp", description: "A stylish pair of Party Glasses, offering UV protection with a modern look.", price: 19.99, stock_quantity: 150 },
  { product_name: "Samsung Galaxy Tab White", product_category: "Tablets", product_image_url: "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp", description: "The Samsung Galaxy Tab White, a versatile tablet suited for work, media, and everyday browsing.", price: 349.99, stock_quantity: 40 },
  { product_name: "Blue Frock", product_category: "Tops", product_image_url: "https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp", description: "A stylish Blue Frock, made from quality fabric for a comfortable, flattering fit.", price: 29.99, stock_quantity: 80 },
  { product_name: "Gray Dress", product_category: "Tops", product_image_url: "https://cdn.dummyjson.com/product-images/tops/gray-dress/thumbnail.webp", description: "A stylish Gray Dress, made from quality fabric for a comfortable, flattering fit.", price: 34.99, stock_quantity: 80 },
  { product_name: "Dodge Hornet GT Plus", product_category: "Vehicle", product_image_url: "https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/thumbnail.webp", description: "The Dodge Hornet GT Plus, a robust vehicle built for performance, comfort, and reliability.", price: 24999.99, stock_quantity: 5 },
  { product_name: "Durango SXT RWD", product_category: "Vehicle", product_image_url: "https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/thumbnail.webp", description: "The Durango SXT RWD, a robust vehicle built for performance, comfort, and reliability.", price: 36999.99, stock_quantity: 5 },
  { product_name: "Prada Women Bag", product_category: "Women's Bags", product_image_url: "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/thumbnail.webp", description: "An elegant Prada Women Bag, combining timeless style with everyday practicality.", price: 599.99, stock_quantity: 40 },
  { product_name: "White Faux Leather Backpack", product_category: "Women's Bags", product_image_url: "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/thumbnail.webp", description: "An elegant White Faux Leather Backpack, combining timeless style with everyday practicality.", price: 39.99, stock_quantity: 80 },
  { product_name: "Green Crystal Earring", product_category: "Women's Jewellery", product_image_url: "https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/thumbnail.webp", description: "An elegant Green Crystal Earring, crafted to add a refined, timeless touch to any outfit.", price: 29.99, stock_quantity: 80 },
  { product_name: "Black & Brown Slipper", product_category: "Women's Shoes", product_image_url: "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/thumbnail.webp", description: "A comfortable pair of Black & Brown Slipper, blending style with everyday wearability.", price: 19.99, stock_quantity: 150 },
  { product_name: "Rolex Datejust Women", product_category: "Women's Watches", product_image_url: "https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp", description: "An elegant Rolex Datejust Women, crafted with precision for timeless, everyday sophistication.", price: 10999.99, stock_quantity: 5 },
  { product_name: "Watch Gold for Women", product_category: "Women's Watches", product_image_url: "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/thumbnail.webp", description: "An elegant Watch Gold for Women, crafted with precision for timeless, everyday sophistication.", price: 799.99, stock_quantity: 40 },
  { product_name: "Backpack", product_category: "Bags", product_image_url: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg", description: "Water-resistant laptop backpack.", price: 49.99, stock_quantity: 55 },
  { product_name: "Gaming Headset Pro", product_category: "Gaming", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp", description: "7.1 surround sound gaming headset with microphone.", price: 7200.00, stock_quantity: 24 },
  { product_name: "Mechanical Gaming Keyboard", product_category: "Gaming", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-charger/thumbnail.webp", description: "RGB mechanical keyboard with blue switches.", price: 6500.00, stock_quantity: 28 },
  { product_name: "Xbox Wireless Controller", product_category: "Gaming", product_image_url: "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-mag-safe-battery-pack/thumbnail.webp", description: "Official Microsoft wireless controller.", price: 9500.00, stock_quantity: 35 },
  { product_name: "PlayStation 5 Console", product_category: "Gaming", product_image_url: "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-duo/thumbnail.webp", description: "Sony PlayStation 5 Disc Edition console.", price: 85000.00, stock_quantity: 12 },
  { product_name: "Gaming Desk XL", product_category: "Gaming", product_image_url: "https://cdn.dummyjson.com/product-images/furniture/office-chair/thumbnail.webp", description: "Large carbon-fiber gaming desk with cable management.", price: 18500.00, stock_quantity: 10 },
  { product_name: "Gaming Mouse", product_category: "Electronics", product_image_url: "https://cdn.dummyjson.com/product-images/85/thumbnail.jpg", description: "RGB gaming mouse.", price: 2800.00, stock_quantity: 50 },
  { product_name: "Running Shoes", product_category: "Footwear", product_image_url: "https://cdn.dummyjson.com/product-images/40/thumbnail.jpg", description: "Lightweight running shoes.", price: 89.99, stock_quantity: 45 },
  { product_name: "Laptop Backpack", product_category: "Accessories", product_image_url: "https://placehold.co/600x400/png?text=Laptop+Backpack", description: "Premium laptop backpack.", price: 4500.00, stock_quantity: 30 },
  { product_name: "Wireless Presenter", product_category: "Accessories", product_image_url: "https://placehold.co/600x400/png?text=Presenter", description: "Wireless presentation remote.", price: 1800.00, stock_quantity: 40 },
  { product_name: "USB Flash Drive 64GB", product_category: "Accessories", product_image_url: "https://placehold.co/600x400/png?text=USB+Drive", description: "Fast USB storage.", price: 1200.00, stock_quantity: 50 },
  { product_name: "Travel Backpack", product_category: "Bags", product_image_url: "https://placehold.co/600x400/png?text=Travel+Backpack", description: "Travel backpack.", price: 5500.00, stock_quantity: 25 },
  { product_name: "Duffel Bag", product_category: "Bags", product_image_url: "https://placehold.co/600x400/png?text=Duffel+Bag", description: "Sports duffel bag.", price: 3900.00, stock_quantity: 18 },
  { product_name: "Messenger Bag", product_category: "Bags", product_image_url: "https://placehold.co/600x400/png?text=Messenger+Bag", description: "Office messenger bag.", price: 4300.00, stock_quantity: 22 },
  { product_name: "Laptop Bag", product_category: "Bags", product_image_url: "https://placehold.co/600x400/png?text=Laptop+Bag", description: "Waterproof laptop bag.", price: 4800.00, stock_quantity: 30 },
  { product_name: "Face Powder", product_category: "Beauty", product_image_url: "https://placehold.co/600x400/png?text=Face+Powder", description: "Beauty face powder.", price: 1500.00, stock_quantity: 40 },
  { product_name: "Lip Gloss", product_category: "Beauty", product_image_url: "https://placehold.co/600x400/png?text=Lip+Gloss", description: "Long lasting lip gloss.", price: 900.00, stock_quantity: 50 },
  { product_name: "Face Foundation", product_category: "Beauty", product_image_url: "https://placehold.co/600x400/png?text=Foundation", description: "Smooth face foundation.", price: 1800.00, stock_quantity: 30 },
  { product_name: "Yoga Mat", product_category: "Fitness", product_image_url: "https://placehold.co/600x400/png?text=Yoga+Mat", description: "Exercise mat.", price: 2500.00, stock_quantity: 30 },
  { product_name: "Skipping Rope", product_category: "Fitness", product_image_url: "https://placehold.co/600x400/png?text=Skipping+Rope", description: "Fitness skipping rope.", price: 700.00, stock_quantity: 50 },
  { product_name: "Dumbbell Set", product_category: "Fitness", product_image_url: "https://placehold.co/600x400/png?text=Dumbbells", description: "20kg dumbbells.", price: 6000.00, stock_quantity: 15 },
  { product_name: "Exercise Ball", product_category: "Fitness", product_image_url: "https://placehold.co/600x400/png?text=Exercise+Ball", description: "Balance ball.", price: 2800.00, stock_quantity: 20 },
  { product_name: "Canvas Shoes", product_category: "Footwear", product_image_url: "https://placehold.co/600x400/png?text=Canvas+Shoes", description: "Canvas sneakers.", price: 3200.00, stock_quantity: 25 },
  { product_name: "Leather Boots", product_category: "Footwear", product_image_url: "https://placehold.co/600x400/png?text=Leather+Boots", description: "Leather boots.", price: 7800.00, stock_quantity: 20 },
  { product_name: "Flip Flops", product_category: "Footwear", product_image_url: "https://placehold.co/600x400/png?text=Flip+Flops", description: "Comfort sandals.", price: 900.00, stock_quantity: 50 },
  { product_name: "Hiking Boots", product_category: "Footwear", product_image_url: "https://placehold.co/600x400/png?text=Hiking+Boots", description: "Mountain boots.", price: 9200.00, stock_quantity: 15 },
  { product_name: "Bookshelf", product_category: "Furniture", product_image_url: "https://placehold.co/600x400/png?text=Bookshelf", description: "Wooden bookshelf.", price: 14500.00, stock_quantity: 8 },
  { product_name: "Wall Clock", product_category: "Home", product_image_url: "https://placehold.co/600x400/png?text=Wall+Clock", description: "Modern wall clock.", price: 2200.00, stock_quantity: 25 },
  { product_name: "Curtains", product_category: "Home", product_image_url: "https://placehold.co/600x400/png?text=Curtains", description: "Living room curtains.", price: 4500.00, stock_quantity: 18 },
  { product_name: "Throw Pillow", product_category: "Home", product_image_url: "https://placehold.co/600x400/png?text=Pillow", description: "Decorative pillow.", price: 1200.00, stock_quantity: 35 },
  { product_name: "Table Lamp", product_category: "Home", product_image_url: "https://placehold.co/600x400/png?text=Lamp", description: "LED table lamp.", price: 3400.00, stock_quantity: 22 },
  { product_name: "MacBook Air M3", product_category: "Laptops", product_image_url: "https://placehold.co/600x400/png?text=MacBook+Air", description: "Apple laptop.", price: 165000.00, stock_quantity: 10 },
  { product_name: "Dell XPS 15", product_category: "Laptops", product_image_url: "https://placehold.co/600x400/png?text=Dell+XPS", description: "Dell premium laptop.", price: 182000.00, stock_quantity: 7 },
  { product_name: "HP Spectre x360", product_category: "Laptops", product_image_url: "https://placehold.co/600x400/png?text=HP+Spectre", description: "Convertible laptop.", price: 174000.00, stock_quantity: 8 },
  { product_name: "Oxford Shirt", product_category: "Men's Shirts", product_image_url: "https://placehold.co/600x400/png?text=Oxford+Shirt", description: "Formal shirt.", price: 2500.00, stock_quantity: 30 },
  { product_name: "Linen Shirt", product_category: "Men's Shirts", product_image_url: "https://placehold.co/600x400/png?text=Linen+Shirt", description: "Summer shirt.", price: 2200.00, stock_quantity: 28 },
  { product_name: "Checked Shirt", product_category: "Men's Shirts", product_image_url: "https://placehold.co/600x400/png?text=Checked+Shirt", description: "Checked shirt.", price: 2400.00, stock_quantity: 22 },
  { product_name: "Polo Shirt", product_category: "Men's Shirts", product_image_url: "https://placehold.co/600x400/png?text=Polo+Shirt", description: "Classic polo.", price: 2100.00, stock_quantity: 40 },
  { product_name: "Ladies Sneakers", product_category: "Women's Shoes", product_image_url: "https://placehold.co/600x400/png?text=Ladies+Sneakers", description: "Fashion sneakers.", price: 4500.00, stock_quantity: 20 },
  { product_name: "High Heels", product_category: "Women's Shoes", product_image_url: "https://placehold.co/600x400/png?text=High+Heels", description: "Elegant heels.", price: 5800.00, stock_quantity: 18 },
  { product_name: "Flat Sandals", product_category: "Women's Shoes", product_image_url: "https://placehold.co/600x400/png?text=Sandals", description: "Comfort sandals.", price: 2400.00, stock_quantity: 30 },
  { product_name: "Ankle Boots", product_category: "Women's Shoes", product_image_url: "https://placehold.co/600x400/png?text=Ankle+Boots", description: "Stylish boots.", price: 6900.00, stock_quantity: 15 },
];

export default async function seed() {
  try {
    // Build one multi-row INSERT: VALUES ($1,$2,$3,$4,$5,$6), ($7,$8,...), ...
    const cols = 6;
    const valuesSql = products
      .map((_, i) => {
        const base = i * cols;
        return `($${base + 1}, $${base + 2}, $${base + 3}, $${base + 4}, $${base + 5}, $${base + 6})`;
      })
      .join(",\n        ");

    const params = products.flatMap((p) => [
      p.product_name,
      p.product_category,
      p.product_image_url,
      p.description,
      p.price,
      p.stock_quantity,
    ]);

    await db.query(
      `INSERT INTO products (
         product_name,
         product_category,
         product_image_url,
         description,
         price,
         stock_quantity
       )
       VALUES
        ${valuesSql}
       ON CONFLICT (product_name)
       DO NOTHING;`,
      params
    );

logger.info(`Database seeded (${products.length} products processed)`);
  } catch (err) {
    logger.error(`Seeding failed: ${err}`);
    process.exitCode = 1;
  } finally {
    process.exit();
  }
}